import { Department, Patient, FloorInfo } from '@/data/hospitalData';

export const printHospitalReport = (
    departments: Department[],
    patients: Patient[],
    floors: FloorInfo[],
    campus: any
) => {
    const today = new Date().toLocaleDateString();

    const html = `
        <!DOCTYPE html>
        <html>
        <head>
            <title>Hospital Navigation Report - ${campus.name}</title>
            <style>
                body { font-family: sans-serif; padding: 40px; color: #333; }
                header { text-align: center; border-bottom: 2px solid #6366f1; margin-bottom: 30px; padding-bottom: 20px; }
                h1 { color: #6366f1; margin: 0; }
                h2 { color: #666; margin: 5px 0; }
                .meta { font-size: 0.9em; color: #888; margin-top: 10px; }
                .section { margin-bottom: 40px; }
                .section-title { font-size: 1.4em; border-left: 5px solid #f59e0b; padding-left: 15px; margin-bottom: 20px; text-transform: uppercase; }
                table { width: 100%; border-collapse: collapse; margin-top: 10px; }
                th { text-align: left; background: #f8fafc; padding: 12px; border-bottom: 2px solid #e2e8f0; font-size: 0.9em; }
                td { padding: 12px; border-bottom: 1px solid #e2e8f0; font-size: 0.9em; }
                .bilingual { font-size: 0.85em; color: #666; display: block; }
                @media print {
                    .no-print { display: none; }
                    body { padding: 0; }
                    .section { break-inside: avoid; }
                }
            </style>
        </head>
        <body>
            <header>
                <h1>${campus.name}</h1>
                <h2>${campus.nameTA}</h2>
                <div class="meta">Hospital Navigation Dataset Report • Generated: ${today}</div>
            </header>

            <div class="section">
                <div class="section-title">Campus Info / வளாக தகவல்</div>
                <p><strong>Address:</strong> ${campus.address}</p>
                <p><strong>Address (TA):</strong> ${campus.addressTA}</p>
                <p><strong>Phone:</strong> ${campus.phone}</p>
            </div>

            <div class="section">
                <div class="section-title">Departments / துறைகள்</div>
                <table>
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name / பெயர்</th>
                            <th>Location / இடம்</th>
                            <th>Room</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${departments.map(d => `
                            <tr>
                                <td>${d.id}</td>
                                <td>${d.name}<span class="bilingual">${d.nameTA}</span></td>
                                <td>Block ${d.block}, Floor ${d.floor}</td>
                                <td>${d.room}</td>
                            </tr>
                        `).join('')}
                    </tbody>
                </table>
            </div>

            <div class="section">
                <div class="section-title">Patients / நோயாளிகள்</div>
                <table>
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name / பெயர்</th>
                            <th>Ward / வார்டு</th>
                            <th>Room / அறை</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${patients.map(p => `
                            <tr>
                                <td>${p.id}</td>
                                <td>${p.name}</td>
                                <td>${p.ward || 'N/A'}</td>
                                <td>${p.room}</td>
                            </tr>
                        `).join('')}
                    </tbody>
                </table>
            </div>

            <footer style="margin-top: 50px; text-align: center; font-size: 0.8em; color: #888;">
                Generated by Hospital Navigation AI System
            </footer>

            <script>
                window.onload = () => {
                    setTimeout(() => {
                        window.print();
                        // window.close(); // Optional: close tab after printing
                    }, 500);
                };
            </script>
        </body>
        </html>
    `;

    const printWindow = window.open('', '_blank');
    if (printWindow) {
        printWindow.document.write(html);
        printWindow.document.close();
    }
};
